/*
 * DCSA OpenAPI specification for Track & Trace
 *
 * API specification issued by DCSA.org
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@dcsa.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// The status of the document in the process. For possible values see reference table ‘Transport Document version reference data entity’.
        /// </summary>
        /// <value>The status of the document in the process. For possible values see reference table ‘Transport Document version reference data entity’.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum DocumentStatus
        {
            /// <summary>
            /// Enum RECEEnum for RECE
            /// </summary>
            [EnumMember(Value = "RECE")]
            RECEEnum = 0,
            /// <summary>
            /// Enum DRFTEnum for DRFT
            /// </summary>
            [EnumMember(Value = "DRFT")]
            DRFTEnum = 1,
            /// <summary>
            /// Enum PENAEnum for PENA
            /// </summary>
            [EnumMember(Value = "PENA")]
            PENAEnum = 2,
            /// <summary>
            /// Enum PENUEnum for PENU
            /// </summary>
            [EnumMember(Value = "PENU")]
            PENUEnum = 3,
            /// <summary>
            /// Enum REJEEnum for REJE
            /// </summary>
            [EnumMember(Value = "REJE")]
            REJEEnum = 4,
            /// <summary>
            /// Enum APPREnum for APPR
            /// </summary>
            [EnumMember(Value = "APPR")]
            APPREnum = 5,
            /// <summary>
            /// Enum ISSUEnum for ISSU
            /// </summary>
            [EnumMember(Value = "ISSU")]
            ISSUEnum = 6,
            /// <summary>
            /// Enum SURREnum for SURR
            /// </summary>
            [EnumMember(Value = "SURR")]
            SURREnum = 7,
            /// <summary>
            /// Enum SUBMEnum for SUBM
            /// </summary>
            [EnumMember(Value = "SUBM")]
            SUBMEnum = 8,
            /// <summary>
            /// Enum VOIDEnum for VOID
            /// </summary>
            [EnumMember(Value = "VOID")]
            VOIDEnum = 9        }
}
