/*
 * DCSA OpenAPI specification for Track & Trace
 *
 * API specification issued by DCSA.org
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@dcsa.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Code to denote whether the equipment is empty or laden.
        /// </summary>
        /// <value>Code to denote whether the equipment is empty or laden.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum EmptyIndicatorCode
        {
            /// <summary>
            /// Enum EMPTYEnum for EMPTY
            /// </summary>
            [EnumMember(Value = "EMPTY")]
            EMPTYEnum = 0,
            /// <summary>
            /// Enum LADENEnum for LADEN
            /// </summary>
            [EnumMember(Value = "LADEN")]
            LADENEnum = 1        }
}
