/*
 * DCSA OpenAPI specification for Track & Trace
 *
 * API specification issued by DCSA.org
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@dcsa.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// The equipment notification entity is a specialization of the notification entity to support specification of data that only applies to an equipment notification.
    /// </summary>
    [DataContract]
    public partial class EquipmentNotification : BaseNotification, IEquatable<EquipmentNotification>
    { 
        /// <summary>
        /// Gets or Sets NotificationType
        /// </summary>
        [DataMember(Name="notificationType")]
        public string NotificationType { get; set; }

        /// <summary>
        /// Unique identifier for Event Type Code. For equipment events this can be: - LOAD (Load) - DISC (Discharge) - GTIN (Gate in) - GTOT (Gate out) - STUF (Stuffing) - STRP (Stripping) 
        /// </summary>
        /// <value>Unique identifier for Event Type Code. For equipment events this can be: - LOAD (Load) - DISC (Discharge) - GTIN (Gate in) - GTOT (Gate out) - STUF (Stuffing) - STRP (Stripping) </value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum NotificationSubtypeEnum
        {
            /// <summary>
            /// Enum LOADEnum for LOAD
            /// </summary>
            [EnumMember(Value = "LOAD")]
            LOADEnum = 0,
            /// <summary>
            /// Enum DISCEnum for DISC
            /// </summary>
            [EnumMember(Value = "DISC")]
            DISCEnum = 1,
            /// <summary>
            /// Enum GTINEnum for GTIN
            /// </summary>
            [EnumMember(Value = "GTIN")]
            GTINEnum = 2,
            /// <summary>
            /// Enum GTOTEnum for GTOT
            /// </summary>
            [EnumMember(Value = "GTOT")]
            GTOTEnum = 3,
            /// <summary>
            /// Enum STUFEnum for STUF
            /// </summary>
            [EnumMember(Value = "STUF")]
            STUFEnum = 4,
            /// <summary>
            /// Enum STRPEnum for STRP
            /// </summary>
            [EnumMember(Value = "STRP")]
            STRPEnum = 5        }

        /// <summary>
        /// Unique identifier for Event Type Code. For equipment events this can be: - LOAD (Load) - DISC (Discharge) - GTIN (Gate in) - GTOT (Gate out) - STUF (Stuffing) - STRP (Stripping) 
        /// </summary>
        /// <value>Unique identifier for Event Type Code. For equipment events this can be: - LOAD (Load) - DISC (Discharge) - GTIN (Gate in) - GTOT (Gate out) - STUF (Stuffing) - STRP (Stripping) </value>
        [DataMember(Name="notificationSubtype")]
        public NotificationSubtypeEnum? NotificationSubtype { get; set; }

        /// <summary>
        /// Gets or Sets EquipmentReference
        /// </summary>
        [DataMember(Name="equipmentReference")]
        public string EquipmentReference { get; set; }

        /// <summary>
        /// Gets or Sets EmptyIndicatorCode
        /// </summary>
        [Required]
        [DataMember(Name="emptyIndicatorCode")]
        public EmptyIndicatorCode EmptyIndicatorCode { get; set; }

        /// <summary>
        /// Gets or Sets TransportCallID
        /// </summary>
        [Required]
        [DataMember(Name="transportCallID")]
        public Guid? TransportCallID { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EquipmentNotification {\n");
            sb.Append("  NotificationType: ").Append(NotificationType).Append("\n");
            sb.Append("  NotificationSubtype: ").Append(NotificationSubtype).Append("\n");
            sb.Append("  EquipmentReference: ").Append(EquipmentReference).Append("\n");
            sb.Append("  EmptyIndicatorCode: ").Append(EmptyIndicatorCode).Append("\n");
            sb.Append("  TransportCallID: ").Append(TransportCallID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((EquipmentNotification)obj);
        }

        /// <summary>
        /// Returns true if EquipmentNotification instances are equal
        /// </summary>
        /// <param name="other">Instance of EquipmentNotification to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EquipmentNotification other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    NotificationType == other.NotificationType ||
                    NotificationType != null &&
                    NotificationType.Equals(other.NotificationType)
                ) && 
                (
                    NotificationSubtype == other.NotificationSubtype ||
                    NotificationSubtype != null &&
                    NotificationSubtype.Equals(other.NotificationSubtype)
                ) && 
                (
                    EquipmentReference == other.EquipmentReference ||
                    EquipmentReference != null &&
                    EquipmentReference.Equals(other.EquipmentReference)
                ) && 
                (
                    EmptyIndicatorCode == other.EmptyIndicatorCode ||
                    EmptyIndicatorCode != null &&
                    EmptyIndicatorCode.Equals(other.EmptyIndicatorCode)
                ) && 
                (
                    TransportCallID == other.TransportCallID ||
                    TransportCallID != null &&
                    TransportCallID.Equals(other.TransportCallID)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (NotificationType != null)
                    hashCode = hashCode * 59 + NotificationType.GetHashCode();
                    if (NotificationSubtype != null)
                    hashCode = hashCode * 59 + NotificationSubtype.GetHashCode();
                    if (EquipmentReference != null)
                    hashCode = hashCode * 59 + EquipmentReference.GetHashCode();
                    if (EmptyIndicatorCode != null)
                    hashCode = hashCode * 59 + EmptyIndicatorCode.GetHashCode();
                    if (TransportCallID != null)
                    hashCode = hashCode * 59 + TransportCallID.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(EquipmentNotification left, EquipmentNotification right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EquipmentNotification left, EquipmentNotification right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
