/*
 * DCSA OpenAPI specification for Track & Trace
 *
 * API specification issued by DCSA.org
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@dcsa.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Code for the event classifier, either PLN (Planned), ACT (Actual), REQ (Requested) or EST (Estimated).
        /// </summary>
        /// <value>Code for the event classifier, either PLN (Planned), ACT (Actual), REQ (Requested) or EST (Estimated).</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum EventClassifierCode
        {
            /// <summary>
            /// Enum PLNEnum for PLN
            /// </summary>
            [EnumMember(Value = "PLN")]
            PLNEnum = 0,
            /// <summary>
            /// Enum ACTEnum for ACT
            /// </summary>
            [EnumMember(Value = "ACT")]
            ACTEnum = 1,
            /// <summary>
            /// Enum REQEnum for REQ
            /// </summary>
            [EnumMember(Value = "REQ")]
            REQEnum = 2,
            /// <summary>
            /// Enum ESTEnum for EST
            /// </summary>
            [EnumMember(Value = "EST")]
            ESTEnum = 3        }
}
