/*
 * DCSA OpenAPI specification for Track & Trace
 *
 * API specification issued by DCSA.org
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@dcsa.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// The Notification Type of the object - to be used as a discriminator.
        /// </summary>
        /// <value>The Notification Type of the object - to be used as a discriminator.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum NotificationType
        {
            /// <summary>
            /// Enum EQUIPMENTEnum for EQUIPMENT
            /// </summary>
            [EnumMember(Value = "EQUIPMENT")]
            EQUIPMENTEnum = 0,
            /// <summary>
            /// Enum SHIPMENTEnum for SHIPMENT
            /// </summary>
            [EnumMember(Value = "SHIPMENT")]
            SHIPMENTEnum = 1,
            /// <summary>
            /// Enum TRANSPORTEnum for TRANSPORT
            /// </summary>
            [EnumMember(Value = "TRANSPORT")]
            TRANSPORTEnum = 2        }
}
