/*
 * DCSA OpenAPI specification for Track & Trace
 *
 * API specification issued by DCSA.org
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@dcsa.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// The code to identify the type of information that is related to the shipment notification.
        /// </summary>
        /// <value>The code to identify the type of information that is related to the shipment notification.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ShipmentInformationType
        {
            /// <summary>
            /// Enum BOKEnum for BOK
            /// </summary>
            [EnumMember(Value = "BOK")]
            BOKEnum = 0,
            /// <summary>
            /// Enum SHIEnum for SHI
            /// </summary>
            [EnumMember(Value = "SHI")]
            SHIEnum = 1,
            /// <summary>
            /// Enum VGMEnum for VGM
            /// </summary>
            [EnumMember(Value = "VGM")]
            VGMEnum = 2,
            /// <summary>
            /// Enum SRMEnum for SRM
            /// </summary>
            [EnumMember(Value = "SRM")]
            SRMEnum = 3,
            /// <summary>
            /// Enum TRDEnum for TRD
            /// </summary>
            [EnumMember(Value = "TRD")]
            TRDEnum = 4,
            /// <summary>
            /// Enum ARNEnum for ARN
            /// </summary>
            [EnumMember(Value = "ARN")]
            ARNEnum = 5        }
}
