/*
 * DCSA OpenAPI specification for Track & Trace
 *
 * API specification issued by DCSA.org
 *
 * OpenAPI spec version: 3.0.0
 * Contact: info@dcsa.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Specifies the type of the transport document (a Bill of Lading (BOL) or a Sea Waybill (SWB)).
        /// </summary>
        /// <value>Specifies the type of the transport document (a Bill of Lading (BOL) or a Sea Waybill (SWB)).</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum TransportDocumentType
        {
            /// <summary>
            /// Enum BOLEnum for BOL
            /// </summary>
            [EnumMember(Value = "BOL")]
            BOLEnum = 0,
            /// <summary>
            /// Enum SWBEnum for SWB
            /// </summary>
            [EnumMember(Value = "SWB")]
            SWBEnum = 1        }
}
